#!/usr/bin/env bash
alias ll='ls -w'
alias dev='quasar dev'
alias pwa='quasar dev -m pwa'
alias ssr='quasar dev -m ssr'
alias nextp='npm verion patch'
alias nextm='npm verion minor'
alias nextmj='npm verion major'
alias ios='quasar dev -m ios'
alias android='quasar dev -m android'
alias nextp='npm verion patch'
alias nextm='npm verion minor'
alias nextmj='npm verion major'
